import type React from "react";

export const inp: React.CSSProperties = {
  background: "#f9fafb",
  border: "1px solid #d1d5db",
  borderRadius: 8,
  padding: "10px 12px",
  color: "#111827",
  fontSize: 14,
  outline: "none",
  width: "100%",
};

export const styles: Record<string, React.CSSProperties> = {
  header:       { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 24 },
  title:        { fontSize: 24, fontWeight: 600, color: "var(--text)", marginBottom: 2 },
  sub:          { color: "var(--text3)", fontSize: 13 },
  addBtn:       { display: "flex", alignItems: "center", gap: 7, background: "#1a1a18", color: "#fff", border: "none", borderRadius: 9, padding: "10px 18px", fontSize: 14, fontWeight: 500, cursor: "pointer" },
  searchWrap:   { display: "flex", alignItems: "center", gap: 10, background: "#fff", border: "1px solid #e5e7eb", borderRadius: 10, padding: "0 14px", marginBottom: 24, maxWidth: 360 },
  searchInput:  { flex: 1, background: "none", border: "none", outline: "none", color: "var(--text)", fontSize: 14, padding: "11px 0" },
  clearBtn:     { background: "none", border: "none", color: "var(--text3)", display: "flex", alignItems: "center", cursor: "pointer" },
  grid:         { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 18 },
  card:         { background: "#ffffff", border: "1px solid #e5e7eb", borderRadius: 12, overflow: "hidden", cursor: "pointer", transition: "box-shadow .15s, transform .15s" },
  imgWrap:      { height: 160, background: "#f3f4f6", display: "flex", alignItems: "center", justifyContent: "center", position: "relative", overflow: "hidden" },
  img:          { width: "100%", height: "100%", objectFit: "cover" },
  statusDot:    { position: "absolute", top: 10, right: 10, width: 8, height: 8, borderRadius: "50%" },
  cardBody:     { padding: "14px 16px" },
  cardCategory: { fontSize: 11, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 5, fontWeight: 500 },
  cardName:     { fontSize: 15, fontWeight: 600, color: "#111827", marginBottom: 5 },
  cardDesc:     { fontSize: 13, color: "#6b7280", marginBottom: 12, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" },
  cardFooter:   { display: "flex", alignItems: "flex-end", justifyContent: "space-between" },
  price:        { fontSize: 16, fontWeight: 700, color: "#111827" },
  stock:        { fontSize: 12, color: "#9ca3af", marginTop: 2 },
  actions:      { display: "flex", gap: 7 },
  actionBtn:    { background: "#f9fafb", border: "1px solid #e5e7eb", borderRadius: 7, padding: "6px 8px", color: "#6b7280", display: "flex", alignItems: "center", cursor: "pointer" },
  deleteBtn:    { color: "#ef4444" },
  empty:        { gridColumn: "1/-1", display: "flex", flexDirection: "column", alignItems: "center", gap: 12, padding: 60, color: "#9ca3af", fontSize: 14 },
  form:         { display: "flex", flexDirection: "column", gap: 14 },
  cancelBtn:    { background: "#f9fafb", border: "1px solid #d1d5db", borderRadius: 8, padding: "9px 18px", color: "#374151", fontSize: 14, cursor: "pointer" },
  saveBtn:      { background: "#1a1a18", color: "#fff", border: "none", borderRadius: 8, padding: "9px 18px", fontSize: 14, fontWeight: 500, cursor: "pointer" },
};

export const mStyles: Record<string, React.CSSProperties> = {
  overlay:  { position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, padding: 20 },
  modal:    { background: "#ffffff", border: "1px solid #e5e7eb", borderRadius: 16, width: "100%", maxWidth: 540, maxHeight: "90vh", overflowY: "auto", animation: "fadeIn .2s ease" },
  mHeader:  { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 24px 0" },
  mTitle:   { fontSize: 18, fontWeight: 600, color: "#111827" },
  closeBtn: { background: "none", border: "none", color: "#6b7280", display: "flex", alignItems: "center", padding: 4, cursor: "pointer" },
};

export const dStyles: Record<string, React.CSSProperties> = {
  modal:         { background: "#ffffff", border: "1px solid #e5e7eb", borderRadius: 20, width: "100%", maxWidth: 820, maxHeight: "90vh", overflowY: "auto", display: "flex", flexDirection: "row", animation: "fadeIn .2s ease" },
  imgPanel:      { width: 340, minWidth: 280, flexShrink: 0, background: "#f9fafb", borderRight: "1px solid #f0f0f0", borderRadius: "20px 0 0 20px", display: "flex", flexDirection: "column", overflow: "hidden", position: "relative" },
  mainImg:       { width: "100%", height: 280, objectFit: "cover", display: "block" },
  noImg:         { height: 280, display: "flex", alignItems: "center", justifyContent: "center", background: "#f3f4f6" },
  navBtn:        { position: "absolute", top: 125, background: "rgba(255,255,255,0.85)", border: "1px solid #e5e7eb", borderRadius: "50%", width: 30, height: 30, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#374151", zIndex: 2 },
  dots:          { position: "absolute", bottom: 0, left: 0, right: 0, display: "flex", justifyContent: "center", gap: 5, padding: "8px 0", background: "linear-gradient(to top, rgba(0,0,0,0.12), transparent)" },
  dot:           { width: 6, height: 6, borderRadius: "50%", border: "none", cursor: "pointer", padding: 0, transition: "background .2s" },
  thumbRow:      { display: "flex", gap: 6, padding: "10px 12px", overflowX: "auto", borderTop: "1px solid #f0f0f0" },
  thumb:         { width: 52, height: 52, flexShrink: 0, borderRadius: 8, overflow: "hidden", border: "none", cursor: "pointer", padding: 0, outlineOffset: 2, transition: "outline .15s" },
  infoPanel:     { flex: 1, padding: "22px 24px 24px", display: "flex", flexDirection: "column", gap: 16, overflowY: "auto" },
  infoHeader:    { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  categoryBadge: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11, fontWeight: 600, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: 6 },
  productName:   { fontSize: 20, fontWeight: 700, color: "#111827", lineHeight: 1.25, margin: 0 },
  statusRow:     { display: "flex", alignItems: "center" },
  statusBadge:   { display: "inline-flex", alignItems: "center", borderRadius: 20, padding: "4px 12px", fontSize: 12, fontWeight: 500 },
  metricsRow:    { display: "flex", gap: 12 },
  metricBox:     { flex: 1, background: "#f9fafb", border: "1px solid #f0f0f0", borderRadius: 12, padding: "12px 16px" },
  metricLabel:   { fontSize: 11, color: "#9ca3af", fontWeight: 500, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 },
  metricValue:   { fontSize: 20, fontWeight: 700, color: "#111827" },
  outOfStock:    { fontSize: 12, fontWeight: 500, color: "#ef4444", marginLeft: 4 },
  descSection:   { background: "#f9fafb", borderRadius: 12, padding: "14px 16px" },
  sectionLabel:  { display: "flex", alignItems: "center", fontSize: 11, fontWeight: 600, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.07em", marginBottom: 8 },
  descText:      { fontSize: 14, color: "#374151", lineHeight: 1.6, margin: 0 },
  actionRow:     { display: "flex", gap: 10, marginTop: 4 },
  editBtn:       { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 7, background: "#1a1a18", color: "#fff", border: "none", borderRadius: 10, padding: "11px 0", fontSize: 14, fontWeight: 500, cursor: "pointer" },
  delBtn:        { display: "flex", alignItems: "center", justifyContent: "center", gap: 7, background: "#fff0f0", color: "#ef4444", border: "1px solid #fecaca", borderRadius: 10, padding: "11px 18px", fontSize: 14, fontWeight: 500, cursor: "pointer" },
};